name: Check
on: [push, fork]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Move to api
        run: cd api
      - name: Install deps
        run: poetry install --only dev --no-root
      - name: Lint
        run: flake8 {models,routes,services,tests,settings.py,main.py}
