name: CI
on: [push, fork]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        working-directory: ./backend/api
        run: |
          pip install flake8==6.1.0
          pip install flake8-bugbear==23.12.2
          pip install pep8-naming==0.13.3

      - name: Lint
        working-directory: ./backend/api
        run: flake8 {models,routes,services,tests,settings.py,main.py}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        working-directory: ./backend/api
        run: |
          pip install pytest==7.4.3
          pip install coverage==7.3.2

      - name: Test
        working-directory: ./backend/api
        run: pytest tests/test*.py
  