name: CI
on: [push, fork]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        working-directory: ./backend/api
        run: |
          pip install poetry
          poetry install --only dev --no-root backend/api

      - name: Lint
        working-directory: ./backend/api
        run: flake8 {models,routes,services,tests,settings.py,main.py}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        working-directory: ./backend/api
        run: |
          pip install poetry
          poetry install --only dev --no-root backend/api

      - name: Test
        working-directory: ./backend/api
        run: pytest tests/test*.py
  